### ISSUE TITLE
{{for}} statement does not render the items in new lines but instead concatenates the collection

### ISSUE THREAD

**Issue by girishc13** [zalando/beard#12]
For example:
{{for user in users}}

<div>{{user.name}}</div>

{{/for}}

The render result is: <div>Gigi</div><div>Gicu</div>

This is fine if the rendering is contained within tags but it cannot be used as a generic listing template. For example to list imports as in previous issue

**Comment by danpersa** [comment]
Fixed by https://github.com/zalando/beard/pull/30
