### ISSUE TITLE
Add {{ comment }} Statement Support

### ISSUE THREAD

**Issue by Cesarla** [zalando/beard#13]
Add support for the {{ comment }} statement. 

Example:

``` beard
{{comment}}Inline Comment{{/comment}}
```

``` beard
{{comment}}
Multiline Comment
{{/comment}}
```

**Comment by danpersa** [comment]
that's one way of doing comments.

another way would be to include them using a special char like:
{{# This is comment #}}

The advantage is that you don't have to type so much 

Also, I'm not sure if we want to include the comments into the AST (abstract syntax tree), as they don't need to be rendered. We can just skip them in the lexer. For a {{comment}}, a scala class needs to be created and then memory consumed while storing the comments in the AST.

**Comment by mo-gr** [comment]
I don't think a comment should make it into the AST. This only encourages bad ideas like magic comments, that actually do things... Throw them out as early as possible...

**Comment by mo-gr** [comment]
Doesn't beard already kind of has comments like so?:

```
{{if false}}
This is basically a comment
{{/if}}
```

**Comment by danpersa** [comment]
I added a similar request to the ticket...

**Comment by axyz** [comment]
I prefer the symbols here: comment is quite a common variable name on frontend scenarios... having it reserved could introduce a lot of confusion for newcomers.

We just have to check if a multiline like

```
{{# 
foo 
bar {{ qux }}
}}

#}}
```

would work :smile:

**Comment by danpersa** [comment]
so we need an unit test for this :)

**Comment by Cesarla** [comment]
Merged!
