### ISSUE TITLE
Add a way to get the index of an element within a {{for}} loop

### ISSUE THREAD

**Issue by Cesarla** [zalando/beard#15]
- Option A
  - :thumbsup: Follows the beard notation
  - :thumbsdown: It can collide with already existing attributes

```
{{for element in elements}}
{{element.index}}
{{/for}}
```
- Option B (Jinja2-alike)
  - :thumbsup: It doesn't populate the namespace
  - :thumbsdown: Adds a new keyword

```
{{for element in elements}}
{{loop.index}}
{{/for}}
```

**Comment by mo-gr** [comment]
I can see at least two more options:

Option C (maybe call it go-style?)

```
{{for element, index in elements}}
{{index}}
{{/for}}
```

Option D (provide a function)

```
{{for el in elements}}
{{index(el)}}
{{/for}}
```

**Comment by axyz** [comment]
of the 2 I prefer Option C, as you are explicitly adding arbitrary names to the scope and having index on the namespace will be optional. In Option D instead you will always have an index function in the namespace.

I think that the less is in the scope without explicitly declaring it, the better it is.

**Comment by danpersa** [comment]
I'd exclude option D, as right now we don't have function support in Beard and I wouldn't like to encourage people add logic while rendering. If you need a function, you should call it in the controller. So maybe option c is best, as you're able to assign whatever name you want to the index.

**Comment by Cesarla** [comment]
I also like option C :+1:

**Comment by Cesarla** [comment]
Merged!
