### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by axyz** [zalando/beard#19]
I was thinking about adding filters like ind handlebars, angular or twig.

basically they are functions for simple text manipulation in order to only have one value in th emodel but various way to represent it.

e.g

```
{{ name | titleCase }}
{{ value | currency(eur) }}
```

that was angular and twig style, while handlebars allows functions to be called as values 
e.g.

```
{{ titleCase name }}
{{ currency value "eur" }}
```

for completeness sake this is the mustache approach to functions:

```
{{#titleCase}} name {{/titleCase}}
```

I prefer the twig/angular implementation as it is way clearer that those are functions and the first identifier you see is the actual value to be rendered.

I'm new to scala but I was thinking about having a type alias (Filter) for function with arbitrary arity that should always return a string. So we can strictly check for them and only allow Filters to be used that way avoiding unwanted behaviors.

**Comment by axyz** [comment]
Regarding to #11 I was thinking to have a `raw` filter defined by default as in twig when we do not want to escape the data.

More in deep my Idea is to have a default behavior to return an object with both the escaped and unescaped representation of the value then the default rendering function will be the toString of the escaped value and filters will just override that function.

raw will be provided by default and it will simply return the toString of the unescaped value.

**Comment by danpersa** [comment]
The most readable version seems the anguar one. And you're easily able to apply more filters without sacrificing the readability.

From the development point of view, we should allow developers to plug-in their own filters. I think the filtering should be extendable.

**Comment by axyz** [comment]
definitely. I think there are 3 possible ways here:

1 - allowing filters to be passed as functions inside the map representing the model
2 - passing a list of functions as an additional (and optional) argument to the rendering function
3 - plugin desired filters when instantiating the "renderer object" itself

the third option may open some "middleware and plugins like" scenario and may be interesting in terms of extensibility of the language.

**Comment by rweyand** [comment]
New point of discussion (since whe already settled for the angular syntax):
Regarding the DateFilter, there is currently the requirement to provide a pre-formatted date string. This is from my perspective nothing you really want. The user should be able to provide the time as a timestamp (in addition to ISO formatted).
Should we include millis/nanos to the filter in some way?
