### ISSUE TITLE
Blocks in between comments are removed

### ISSUE THREAD

**Issue by danpersa** [zalando/beard#29]
``` html
<div>First</div>
{{# this for should render an end of line after each line in the iteration #}}
<div>Hello</div>
{{# this for is similar with the first one #}}
<div>Last</div>
```

is rendered

``` html
<div>First</div>
<div>Last</div>
```

instead of

``` html
<div>First</div>
<div>Hello</div>
<div>Last</div>
```

see the `div-in-between-comments-bug` branch for failing tests

**Comment by danpersa** [comment]
@Cesarla, maybe you can take a look :)

**Comment by Cesarla** [comment]
@danpersa I know what it is happening, I will try to send a PR soon.

**Comment by Cesarla** [comment]
@danpersa It will need to add  `'{{#'` and  `'#}}'` as tokens, otherwise they will be captured as `TEXT`.

**Comment by danpersa** [comment]
If you're doing this, could you also change the comments tokens from `{{#` and `#}}` to `{{-` and `-}}`.

I find them looking better and are also easier to type.
