### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by danpersa** [zalando/beard#37]
Benchmark beard against:
https://github.com/mwunsch/handlebars.scala

And maybe other frameworks.

**Comment by lasomethingsomething** [comment]
Hey @danpersa, can we close this issue? It dates back to March 2016.

Or, we could add a "Help Wanted" label.

**Comment by danpersa** [comment]
Added the help wanted label

**Comment by danpersa** [comment]
We have a set of benchmarks
