### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by benoit-ponsero** [zalando/beard#57]
Hello,

I just noticed that the documentation contains informations on filters when they have not yet been released in 0.0.6

I think it would be better to be able to choose specific release documentation

**Comment by danpersa** [comment]
We'll release the next version next week, with all the latest features. We'll think on how to keep the docs in sync with the code.

**Comment by danpersa** [comment]
- released the 0.1.0 version
- added a  [changelog](https://github.com/zalando/beard/blob/master/CHANGELOG.md)
