### ISSUE TITLE
Chaining filters

### ISSUE THREAD

**Issue by benoit-glevarec** [zalando/beard#61]
Hi,

It seems that there is a problem while chaining filters

The following code 
`{{test | title | reverse}} <br>`
`{{test | reverse | title}} <br>`
`{{test | title}} <br>`
`{{test | reverse}} <br>`

With context `{ "test": "test me without reverse"}`

Results :

esrever tuohtiw em tset 
Test Me Without Reverse 
Test Me Without Reverse 
esrever tuohtiw em tset

**Comment by danpersa** [comment]
I'll take a look :)

**Comment by benoit-glevarec** [comment]
Perfect thanks 👍

**Comment by danpersa** [comment]
I just published v0.1.1 which includes this fix.
