### ISSUE TITLE
Need support to scala 2.13..

### ISSUE THREAD

**Issue by andares** [zalando/beard#79]
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: de.zalando#beard_2.13;0.2.0: not found

😂

**Comment by danpersa** [comment]
@andares I'll look into it soon :)
Also feel free to contribute :)

**Comment by danpersa** [comment]
I looked into it, for now, it is blocked by monix supporting scala 2.13: https://github.com/monix/monix/issues/862

**Comment by danpersa** [comment]
https://github.com/scalameter/scalameter/issues/213 is also a blocker for this

**Comment by andares** [comment]
I see, that's ok, scala 2.13 version is really new. 😹

**Comment by danpersa** [comment]
I'll keep the ticket open, I'll fix it as soon as the dependencies are upgraded.

**Comment by danpersa** [comment]
@andares I published beard 0.3.0 with support for Scala 2.13
