### ISSUE TITLE
0.3 on Scala 2.12

### ISSUE THREAD

**Issue by alexjg** [zalando/beard#82]
Beard looks like a great library and we would love to use it. Unfortunately we're stuck on Scala 2.12 for the time being, is there any reason this library can't be released for 2.12?

**Comment by danpersa** [comment]
I've published the 0.3.1 version with scala 2.12 support in bintray: https://dl.bintray.com/zalando/maven/de/zalando/beard_2.12/0.3.1/

Enjoy and feel free to contribute!

**Comment by alexjg** [comment]
Amazing, thank you for the quick response. I'll keep an eye out for opportunities to contribute.
