### ISSUE TITLE
Error in maven package?

### ISSUE THREAD

**Issue by dev590t** [zalando/beard#84]
In the maven repository, the file https://dl.bintray.com/zalando/maven/de/zalando/beard_2.13/0.3.1/beard_2.13-0.3.1.pom use antlr-runtime 4.7.2. But the build.sbt use antlr version is 4.8-1. This is normal?

I have this warning when I try to launch the program.
```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8
```

The problem is solved when I use the package beard that I compile in my local machine.

**Comment by danpersa** [comment]
The maven file gets generated by the scala release plugin. It is not normal to use a different version of the antlr-runtime.

Probably there is a bug in the generator :(

I would recommend using sbt instead of maven.

**Comment by danpersa** [comment]
Should be fixed by: https://github.com/zalando/beard/pull/83
