### ISSUE TITLE
Problem fetching package from https://dl.bintray.com/zalando/maven

### ISSUE THREAD

**Issue by mmaqueda-zalando** [zalando/beard#86]
I am trying to retrieve the package from the Bintray repository but it seems that the service is no longer available.

I am trying to check in maven.zalando.net but seems that is not there either, can you please help me with this?

Thanks

**Comment by benj--** [comment]
+1

**Comment by kfontorbe** [comment]
+1

**Comment by henriquerezendezalando** [comment]
+1

**Comment by mventuravoyageprive** [comment]
+1

**Comment by albeatoc** [comment]
I get java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/zalando/maven/de/zalando/beard_2.12/0.2.0/beard_2.12-0.2.0.pom 

Seems that version was removed at some point and the new version only supports JSK 14+
[](https://github.com/zalando/beard/issues/85)

**Comment by albeatoc** [comment]
Bintray seems to be dead: https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

**Comment by zhao-li** [comment]
Sorry, I'm new to Scala and SBT.

When I tried to execute `sbt update`, I get this error:
```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading de.zalando:beard_2.12:0.3.1
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localde.zalando/beard_2.12/0.3.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/de/zalando/beard_2.12/0.3.1/beard_2.12-0.3.1.pom
[error]   forbidden: https://dl.bintray.com/zalando/maven/de/zalando/beard_2.12/0.3.1/beard_2.12-0.3.1.pom
[error] Total time: 4 s, completed Nov 19, 2021 7:36:03 PM
```

I'm guessing it's related to Bintray going away mentioned here.

Is there another method to install this dependency?

Thank you for your time and help 🙏

**Comment by albeatoc** [comment]
You need to move to scalate that also supports the mustache format or or build the project and publish it to your own repo. I dont think this project is maintained any more.

**Comment by zhao-li** [comment]
@albeatoc thanks for the heads up.  I was trying to get Scalate, Twirl, or Beard working, but was only able to get ScalaTags working.  Would you happen to have a project that uses Scalate within sbt that is working?  Just thought I'd ask.  Thanks again for the heads on Beard being unmaintained.  Take care 🙏

**Comment by leviferreira** [comment]
This repo is now unmaintained and will be archived.
